name: CI

on: [push, pull_request]

jobs:
  flatpak:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:6
      options: --privileged

    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        bundle: com.github.manexim.typewriter.flatpak
        manifest-path: com.github.manexim.typewriter.yml

        run-tests: true

        repository-name: appcenter
        repository-url: https://flatpak.elementary.io/repo.flatpakrepo
        cache-key: "flatpak-builder-${{ github.sha }}"

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: elementary/actions/vala-lint@master
